#ifndef _DEFINE_H
#define _DEFINE_H

/**
	PIN_ON_TOP = 		0
	PIN_ON_LEFT = 	1
	PIN_ON_BOTTOM =	2
	PIN_ON_RIGHT = 	3
*/
#define ORIENTATION_SETTING 2

#ifndef ARM_MATH_CM4
	#define ARM_MATH_CM4
#endif

#define CLIMBING_PNEU PNEU_1
#define SHOOTING_PNEU PNEU_2
#define LAUGHING_PNEU PNEU_3

#define JOYSTICK_UP JS_BUT_A
#define JOYSTICK_RIGHT JS_BUT_B
#define JOYSTICK_DOWN JS_BUT_C
#define JOYSTICK_LEFT JS_BUT_D

#define WALL_LIMIT_SWITCH LIM_SW_1

#endif 
